### ISSUE TITLE
Add support for new OS's

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/swiftly#111]
New Linux platforms supported:
Ubuntu 23.10 (x86_64 and AArch64)
Ubuntu 24.04 (x86_64 and AArch64)
Debian 12 (x86_64 and AArch64)
Fedora 39 (x86_64 and AArch64)

**Comment by futurejones** [comment]
Ubuntu 23.10 is just an interim release and reaches EOL (end of life) in July 2024. 
Is `swiftly` going remove the installation of OS versions once they reach EOL?

**Comment by adam-fowler** [comment]
> Ubuntu 23.10 is just an interim release and reaches EOL (end of life) in July 2024. Is `swiftly` going remove the installation of OS versions once they reach EOL?

While Apple make the tarballs available I don't think there is any harm in providing access.

**Comment by adam-fowler** [comment]
#115
