### ISSUE TITLE
Uninstall deleted active swift version, not the specified. 

### ISSUE THREAD

**Issue by carlynorama** [swiftlang/swiftly#140]
Hi, I was running 0.2.0, but just today updated to 0.3.0 by running the install script without deleting the previous version of swiftly because 0.2.0 didn't have update working yet. 

I went to delete a toolchain I wasn't going to use anymore, and instead it deleted the active toolchain and switched to the one I was deleting. 

It was fine, I recovered easily in this case, but should nuke swiftly and all it's folders from orbit to make the move from 0.2.0 -> 0.3.0 or a problem with the actual `uninstall` command? 

In window one:

```bash
user:~$ swiftly list
Installed release toolchains
----------------------------
Swift 5.10.0
Swift 5.9.2

Installed snapshot toolchains
-----------------------------
main-snapshot-2024-07-15 (in use)
5.10-snapshot-2024-02-14
main-snapshot-2024-02-14
```
In window 2, just for full disclosure
```bash
user:~$ swiftly install latest
...
Swift 5.10.1 installed successfully!
```

Back in window 1
```bash
user:~$ swiftly uninstall 5.10.0
The following toolchains will be uninstalled:
  Swift 5.10.0
Proceed? (Y/n): Y

Error: Found symlink that points to non-swiftly managed executable: /home/eloise/.local/share/swiftly/toolchains/main-snapshot-2024-07-15/usr/bin/repl_swift
user:~$ swiftly list
Installed release toolchains
----------------------------
Swift 5.10.1
Swift 5.10.0 (in use)
Swift 5.9.2

Installed snapshot toolchains
-----------------------------
5.10-snapshot-2024-02-14
main-snapshot-2024-02-14
```

I think the mistake (if its in the code and not the lack of fresh install) has to be in: https://github.com/swiftlang/swiftly/blob/bcfd8439a078893c11d3331c193e2b6a7b431887/Sources/Swiftly/Uninstall.swift

Because I don't see how this could have gone wrong? (I'm on Linux)
https://github.com/swiftlang/swiftly/blob/bcfd8439a078893c11d3331c193e2b6a7b431887/Sources/LinuxPlatform/Linux.swift#L108

**Comment by carlynorama** [comment]
rm'd the appropriate directories (found by `find ~ -iname *swiftly*` or you know the [directions](https://github.com/swiftlang/swiftly/issues/84#issuecomment-2155729037) ) and reinstalled. 

Issue disapears.

**Comment by adam-fowler** [comment]
@carlynorama When you say you ran swiftly in 2 windows did you do that at the same time?
Because if that is the order you ran the different commands it doesn't seem to make sense.
ie the main snapshot was the in use version of swift but when you ran `update` it updated the 5.10 install

**Comment by carlynorama** [comment]
Yes, at the same time.  Let's see if i can clear it up bit. 

### Before the submitted logs

- I ran `curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash`, then option 1 to "update" my 0.2.0 install to 0.3.0, did nothing to deinstall swiftly or the toolchain before hand.  I did the full "it's Friday night. YOLO. Let's just see."
- Afterwards I ran `swiftly install main-snapshot` and switched to it using `use`, no problems.

### The story begins

- Window 1: I did a `list`, it does not list 5.10.1 (latest) because I hadn't installed that yet, but it does list main-snapshot-2024-07-15 (in use) and all the previous toolchains I had with v0.2.0.
- Window 2: I started the `swiftly install latest`
- Window 1: While that Window 2 install was running (I know, I know) I did the `swiftly uninstall 5.10.0` because I wasn't going to need it. 
- After confirming yes (Y) I wanted 5.10.0 deleted in Window 1, I went away from that machine entirely for... a few minutes? 
- When I came back:
  - Window 2: indicated successful install of 5.10.1
  - Window 1: noticed error about folder permissions, ran `list` again to check that 5.10.0 had been deinstalled. Instead I saw:
    - confirmation the 5.10.1 had indeed been successful installed as expected from the Window 2 data
    - main-snapshot-2024-07-15 had been removed and the current swift toolchain had been swapped to the one I had been trying to remove (5.10.0)
- reinstalled main-snapshot-2024-07-15, everything seemed fine, but didn't switch to it. 

Super weird.  I submitted the issue and stopped for the night. 

### This Morning

This morning I noticed there was still some swiftly-not-allowed-to-access messages when trying to switch toolchains with `use`. I figured that this really must be my sloppy install hygine, and decided to clear everything swiftly out and start fresh. I did not do an `ls -al` on these directories to check their permissions. That would have been good data to have in hindsight. 

It seems to all be working now. I installed `latest`, `main-snapshot` (which I needed to do twice? I'm not really sure what that was about, I was relying on list, I did not check the folder, which also would have been useful to have done in retrospect) a `5.9`, then deleted the 5.9, which behaved as expected. 

This is a wee little Ubuntu machine I can wipe with very low stress. Would it be helpful for me to delete swiftly again, uninstalling the toolchains correctly this time, reinstall 0.2.0, and try to recreate? I'm comfortable calling this user error, but if there's data wanted, I can try to collect it.

**Comment by carlynorama** [comment]
Note, using `use` stopped working, nor could I fully uninstall all. Was getting a "The file doesn't exist." for both failures. 

Did 
```
rm -r ~/.local/bin/swiftly 
rm -r ~/.local/share/swiftly/ 
```
AND
```
find ~/.local/bin/ -maxdepth 1 -type l 
find ~/.local/bin/ -maxdepth 1 -type l -delete
```

THEN reinstalled 0.3.0

NOW everything really works as expected.

**Comment by adam-fowler** [comment]
I think the fact you were running swiftly in two windows at the same time is probably the issue. We haven't tested for this at all.

**Comment by carlynorama** [comment]
I agree with that assessment. Surviving multi-window-operation is a a big big lift. I wouldn't honestly actually really expect it from a 0.3.0, as I said I was dinking around too fast on a Friday on an inconsequential dev box.  Did want to note manual deleting the symlinks for the next time I get myself into a jam. 

Thanks for even taking a look!
