### ISSUE TITLE
Swiftly doesn't reliably install dependencies

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swiftly#144]
For the full discussion, see [this thread](https://swift-open-source.slack.com/archives/C04MRUD6VH8/p1721544445770479) in Swift Open Source Slack.

Apparently Swiftly did not automatically install `libcurl4-openssl-dev` on my fresh VPS, which caused build failures when using `--static-swift-stdlib`.

For the sake of search-ability if someone steps into this issue, here's also part of the error pasted here:
```
error: link command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld.gold: error: cannot find -lcurl
/root/.local/share/swiftly/toolchains/5.10.1/usr/lib/swift_static/linux/libFoundationNetworking.a(CFURLSessionInterface.c.o):CFURLSessionInterface.c:function CFURLSessionEasyCodeDescription: error: undefined reference to 'curl_easy_strerror'
```

I know the "find what dependencies to install" logic is not bulletproof and reads from the Dockerfiles, and that Swiftly is waiting on official ways to know what dependencies to install.

I did check the Dockerfiles, all seem to include `libcurl4-openssl-dev` for Ubuntu 22.04.

**Comment by adam-fowler** [comment]
Hmmm I really can't see how that happens as it installs what's in the Dockerfiles. But yeah we are waiting on a better method to decide on dependencies, so this probably won't get looked into.

**Comment by MahdiBM** [comment]
> I really can't see how that happens 
 
 Me too, but it appears to me that it did happen 😅.

**Comment by MahdiBM** [comment]
Someone else also reporting a not-installed dependency in Vapor's Discord server.
Here's [the last message](https://discord.com/channels/431917998102675485/519613337638797315/1267152621689372692) of the conversation related to this issue. Just leaving it here as proof.

**Comment by MahdiBM** [comment]
I see there is a test [here](https://github.com/swiftlang/swiftly/blob/9185e5a92a9b5dfc8833f493e9e0860cf91ecde0/install/tests/default-install.sh#L139C14-L139C27) as well. Not sure what could be going wrong there (though in my limited bash experience, anything can go wrong at all times).

**Comment by adam-fowler** [comment]
Given the changes in #127 I don't think this is valid anymore.

**Comment by MahdiBM** [comment]
Hmmm it still relies on the dockerfiles?
Though to be honest I don't think the issue was from parsing dockerfiles or something.
