### ISSUE TITLE
Enhance the swiftly release build logic

### ISSUE THREAD

**Issue by cmcgee1024** [swiftlang/swiftly#146]
The current script for building a release assumes that the only artifacts will be single static binaries, and at the moment it's only making Linux binaries for the supported architectures (x86_64, and aarch64).

This process should be changed to better align with the sorts of artifacts that comes with Swift toolchains at swift.org, such as the tar.gz archives. Also, there should be a macOS pkg installer with a lipo-ed binary that works on both x86_64, and arm64 macOS.

The self-install logic should be reconfigured to work with these types of artifacts moving forward. Also, the self-upgrade will need to be changed.

**Comment by cmcgee1024** [comment]
Since shell scripts can be problematic in various ways, an idea could be to make an executable target that performs the release build.

**Comment by adam-fowler** [comment]
I would prefer we use a GitHub action for automating the generation of releases

**Comment by cmcgee1024** [comment]
Note that the self upgrade logic needs to be updated to query a swift.org API (to be proposed and discussed on the forums) to discover what the current swiftly version is, and work with the shape of the artifacts of the releases for each respective platform.

**Comment by cmcgee1024** [comment]
This is complete. The new release logic can be invoked using `swift run build-swiftly-release` on macOS or Linux to produce the release artifacts.
