### ISSUE TITLE
Support for Ubuntu 24.04, 23.10, Fedora 39, Debian 12

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/swiftly#152]
There is a PR for adding this to the install script, but now we have moved most of the install code into the swiftly binary we should add this support to the binary

**Comment by vsarunas** [comment]
@adam-fowler / @patrickfreed / @cmcgee1024 , do you need any assistance for having Ubuntu 24.04 support?

Or is there a 2 step process; make the #115 available since work has already been done and then remove once swiftly binary is ready to do those steps? https://github.com/swiftlang/swiftly/pull/161 looks to be also be in a similar situation.

**Comment by cmcgee1024** [comment]
@vsarunas updates to the pull request is welcome and/or new pull requests are welcome.

There are several places in the code that would need to be changed to add Ubuntu 24.04 support. We're hoping to make it easier to manage this in the future using swift.org API. For now, I would use Ubuntu 22.04 as a guide to add 24.04. Some key areas to update:

* Add a new static for it to PlatformDefinition to signal support
* Add a prompt and auto-detection for it in Sources/Linux/LinuxPlatform.swift
* Put the list of required system packages for it in Sources/Linux/LinuxPlatform.swift (derived from the docker file sources)
* Use the new static platform definition for the swift.org API handling in Sources/SwiftlyCore/HTTPClient.swift
* Create a new 24.04 docker compose file in docker/
* We still have the old installer shell script in install/ that would need to be updated too for completeness
* Updates to tests to get coverage for the platform in Tests/ and install/tests/

**Comment by svanimpe** [comment]
Is it safe to use swiftly on Ubuntu 24.04?
It appears to works fine if I select 22.04 during installation.

**Comment by adam-fowler** [comment]
The install script PR for 2404 never got updated. Everything is moving to run from the executable and the install script is pretty much being removed. I don't know timings on when a new release is going to be though.

**Comment by svanimpe** [comment]
Same here. I've had to revert from Swiftly back to https://swiftlang.xyz, just to get 24.04 support.

**Comment by cmcgee1024** [comment]
Thanks everyone for your patience. We're trying to move these issues forward and get a preview release out on swift.org. This one is tagged as a release candidate for that release.

**Comment by cmcgee1024** [comment]
See #173 for a fresh path that should address this.

**Comment by xtremekforever** [comment]
Okay nice! This is great progress!

**Comment by cmcgee1024** [comment]
This is fixed with #173 

Ubuntu 23.10 was not added since it is end of life.

**Comment by pwsacademy** [comment]
@cmcgee1024 When is this going to be released?

I maintain student-friendly installation instructions over at https://github.com/pwsacademy/swift-setup. With Neil's APT repository (https://swiftlang.xyz) shutting down (again), and swiftly not yet supporting Ubuntu 24.04, my instructions are currently broken, and I would have to revert back to a commit from 2020 (using tarballs) 😕
