### ISSUE TITLE
Drop usage of GitHub API

### ISSUE THREAD

**Issue by patrickfreed** [swiftlang/swiftly#157]
#153 updates swiftly to use swift.org-based APIs for most queries, but it still falls back to GitHub for pre-6.0 snapshots. I think we should consider just dropping GitHub API support altogether so that we don't have to maintain two different ways of getting toolchain information. Of course, the cost would be missing information older snapshots, but in my opinion that's worth for the simplification / consolidation it would provide. It's also possible (is it?) that swift.org could start returning results for those older snapshots in the future.

**Comment by 0xTim** [comment]
Since we control Swift.org I don't see why we can't add that info, it should be there in the [data](https://github.com/swiftlang/swift-org-website/tree/main/_data/builds)

**Comment by patrickfreed** [comment]
Do we control the bot that updates that data though? I think that's more where the issue is, at least for 5.0 snapshots. For older branches, yeah we could just fill in that data once ourselves.

**Comment by 0xTim** [comment]
Do you have a link to the API? I can find out

**Comment by shahmishal** [comment]
How back does swiftly support dev snapshots? I don't think people should be using dev snapshots after the first release of the given version. 

For example, you would need to only add dir for each version.  https://github.com/swiftlang/swift-org-website/tree/main/api/v1/install/dev

**Comment by 0xTim** [comment]
Also, yes please 😅 

```
Run swiftly install "${REQUESTED_TOOLCHAIN}"
Error: received status "403 Forbidden" when reaching https://api.github.com/repos/apple/swift/releases?per_page=100&page=1: {"message":"API rate limit exceeded for 20.253.152.177. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by cmcgee1024** [comment]
The GitHub API has been dropped in swiftly. Closing this issue.
