### ISSUE TITLE
Swift 6.0.1 not available in swiftly?

### ISSUE THREAD

**Issue by xtremekforever** [swiftlang/swiftly#171]
Today I saw that Swift 6.0.1 was announced:

https://forums.swift.org/t/announcing-swift-6-0-1/74940

However, I went to install it with `swiftly` (which I love, thanks guys!), but got this:

```bash
$ swiftly install latest
Fetching the latest stable Swift release...
Swift 6.0.0 is already installed, exiting.
```

Why is Swift 6.0.1 not available via Swiftly? Is this something that needs to be manually updated somehow? I do see that the Swift download page does have 6.0.1 available for my platform (which is Ubuntu 22.04):

![image](https://github.com/user-attachments/assets/e6446d41-f5cb-436b-93e3-85e8a9a069e2)

**Comment by zaneenders** [comment]
run `swiftly install 6.0.1`

**Comment by xtremekforever** [comment]
Okay, that works. Why would it not show up as the "latest" version of Swift though, if I may ask?

**Comment by xtremekforever** [comment]
Okay I guess this answers my question. They created a new release for 6.0.1 on this page:

https://github.com/swiftlang/swift/releases

And now I can do `swiftly install latest` and get 6.0.1. Thanks!
