### ISSUE TITLE
Adopt swift-openapi-generator for the GitHub client

### ISSUE THREAD

**Issue by czechboy0** [swiftlang/swiftly#175]
swiftly makes API calls to GitHub and today that client code is hand maintained, requiring careful work to update it as the GitHub API evolves.

It'd be easier to just generate the client code from the GitHub OpenAPI document using swift-openapi-generator. We can filter only the operation(s) needed, without generating or compiling any other generated code.

**Comment by czechboy0** [comment]
Might be unnecessary if the GitHub client is removed: https://github.com/swiftlang/swiftly/issues/166

**Comment by cmcgee1024** [comment]
We no longer user the GitHub API for anything in swiftly, so I'm closing this issue.
