### ISSUE TITLE
Implement macOS support

### ISSUE THREAD

**Issue by patrickfreed** [swiftlang/swiftly#21]
This is a tracking issue for macOS support. More details will be added as that work is scoped out.

Once Linux has reached MVP status, this will be addressed.

**Comment by iainsmith** [comment]
HI @patrickfreed, I was looking at this quickly and was wondering what's needed for this:

- Update Package.swift
- Implement MacPlatform.swift and `struct Mac: Platform` (or would you prefer Darwin) as the name here?

I'd be keen to look at an existing branch, if one exists.

**Comment by sdavids** [comment]
https://github.com/swiftlang/swiftly/blob/364b02bb2904cff62a604bfa4a0ef0d1d9164cd5/DESIGN.md?plain=1#L57


Please honor XDG conventions on MacOS also—Mac users prefer uncluttered home directories too 😉

**Comment by cmcgee1024** [comment]
This has been implemented in #121
