### ISSUE TITLE
Implement `list-available` command on Linux

### ISSUE THREAD

**Issue by patrickfreed** [swiftlang/swiftly#4]
The list-available command accepts a toolchain selector and prints the various toolchains that are available to install (including those already installed) matching that selector. If no selector is provided, all of the toolchains available to install are selected. Alternatively, we can list the newest toolchain from each major.minor combination, as well as the latest snapshot available from the main branch and any major.minor snapshot releases.

For the MVP, this will be implemented using the GitHub tags API on the apple/swift repository.

This is currently mostly implemented, but it doesn't work for snapshots.

**Comment by cmcgee1024** [comment]
This sub command is now available, so I'm closing this.
